# Generated by Django 3.2.16 on 2023-01-15 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
