# Generated by Django 3.2.16 on 2023-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_roles_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pname', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('guardian', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=3)),
                ('dateofadm', models.DateTimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('caseid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=255)),
                ('bed', models.CharField(max_length=10)),
                ('entryBy', models.CharField(max_length=255)),
            ],
        ),
    ]
