# Generated by Django 3.2.16 on 2023-01-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_invoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
