# Generated by Django 3.2.16 on 2023-01-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_invoices_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateofadm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
