# Generated by Django 3.2.16 on 2023-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_staff_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('datetime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
    ]
