# Generated by Django 3.2.16 on 2023-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_wardsbeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qual', models.CharField(max_length=255)),
                ('spec', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('did', models.CharField(max_length=255)),
            ],
        ),
    ]
