# Generated by Django 3.2.16 on 2023-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_doctor_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.CharField(default=500, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='+918756260980', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='did',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
